insert into state (state, name) values ('AK', 'Alaska');
insert into state (state, name) values ('AL', 'Alabama');
insert into state (state, name) values ('AR', 'Arkansas');
insert into state (state, name) values ('AZ', 'Arizona');
insert into state (state, name) values ('CA', 'California');
insert into state (state, name) values ('CO', 'Colorado');
insert into state (state, name) values ('CT', 'Connecticut');
insert into state (state, name) values ('DC', 'District of Columbia');
insert into state (state, name) values ('DE', 'Delaware');
insert into state (state, name) values ('FL', 'Florida');
insert into state (state, name) values ('GA', 'Georgia');
insert into state (state, name) values ('HI', 'Hawaii');
insert into state (state, name) values ('IA', 'Iowa');
insert into state (state, name) values ('ID', 'Idaho');
insert into state (state, name) values ('IL', 'Illinois');
insert into state (state, name) values ('IN', 'Indiana');
insert into state (state, name) values ('KS', 'Kansas');
insert into state (state, name) values ('KY', 'Kentucky');
insert into state (state, name) values ('LA', 'Louisiana');
insert into state (state, name) values ('MA', 'Massachusetts');
insert into state (state, name) values ('MD', 'Maryland');
insert into state (state, name) values ('ME', 'Maine');
insert into state (state, name) values ('MI', 'Michigan');
insert into state (state, name) values ('MN', 'Minnesota');
insert into state (state, name) values ('MO', 'Missouri');
insert into state (state, name) values ('MS', 'Mississippi');
insert into state (state, name) values ('MT', 'Montana');
insert into state (state, name) values ('NC', 'North Carolina');
insert into state (state, name) values ('ND', 'North Dakota');
insert into state (state, name) values ('NE', 'Nebraska');
insert into state (state, name) values ('NH', 'New Hampshire');
insert into state (state, name) values ('NJ', 'New Jersey');
insert into state (state, name) values ('NM', 'New Mexico');
insert into state (state, name) values ('NV', 'Nevada');
insert into state (state, name) values ('NY', 'New York');
insert into state (state, name) values ('OH', 'Ohio');
insert into state (state, name) values ('OK', 'Oklahoma');
insert into state (state, name) values ('OR', 'Oregon');
insert into state (state, name) values ('PA', 'Pennsylvania');
insert into state (state, name) values ('RI', 'Rhode Island');
insert into state (state, name) values ('SC', 'South Carolina');
insert into state (state, name) values ('SD', 'South Dakota');
insert into state (state, name) values ('TN', 'Tennessee');
insert into state (state, name) values ('TX', 'Texas');
insert into state (state, name) values ('UT', 'Utah');
insert into state (state, name) values ('VA', 'Virginia');
insert into state (state, name) values ('VT', 'Vermont');
insert into state (state, name) values ('WA', 'Washington');
insert into state (state, name) values ('WI', 'Wisconsin');
insert into state (state, name) values ('WV', 'West Virginia');
insert into state (state, name) values ('WY', 'Wyoming');
insert into state (state, name) values ('XX', 'Unknown');